#
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#
# development:
#   <<: *default
#   database: PetCare_development
#
#
# test:
#   <<: *default
#   database: PetCare_test
#
#
# production:
#   <<: *default
#   database: PetCare_production
#   username: PetCare
#   password: <%= ENV['PETCARE_DATABASE_PASSWORD'] %>

default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: PetCare_development
test:
  <<: *default
  database: PetCare_test
production:
  <<: *default
  database: PetCare_production
  username: PetCare
  password: <%= ENV['PETCARE_DATABASE_PASSWORD'] %>
